# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c00587fe44e4c47fa5acf3700b032bb6452de0cfd4cdc1c5197cbe57455576c147519a9d78362a733e5881eb37a78e07d04cf8869ca4a35d279c22dc53d093

test:
  secret_key_base: 8e9c402faa04b7581b80220a38045bd84744a8b8ad50525cccd03058d662459cecc066136c10d82f6cd77da66265a4d43d05de9e83edb328acca79b18b1000ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
